feat: new version on columns block
bitdefender/www-websites pull request #115
Opened 2024-05-29 12:35 UTC by ltiseanu

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--www-websites--bitdefender.hlx.page/drafts/lucia-test/
- After: https://datalayer-update--www-websites--bitdefender.hlx.page/drafts/lucia-test/
- 
Prev link:
https://image-card-vsb--www-websites--bitdefender.hlx.page/en-us/fragments/vsb/image-cards-vsb

2024-05-29 12:42 UTC, Matei-Iordache requested changes
In the columns.js block, please add the following:

1. `export default function decorate(block, options) {` add the options parameter to decorate function.
2. `window.dispatchEvent(new CustomEvent('shadowDomLoaded'), {
      bubbles: true,
      composed: true, // This allows the event to cross the shadow DOM boundary
    });`
Add this event at the end of the block.
3. Make sure to extract the metadata like this `const {
    test, test2
  } = options ? options.metadata : block.closest('.section').dataset;`
4. Add this piece of code at the beginning of the decorate function `if (options) {
    // eslint-disable-next-line no-param-reassign
    block = block.querySelector('.block');
    let blockParent = block.closest('.section');
    blockParent.classList.add('we-container');
  }`

2024-05-29 13:32 UTC, enake approved these changes

2024-05-29 13:59 UTC, inastase approved these changes

2024-05-29 14:18 UTC, Matei-Iordache requested changes
When imported to aem, the component is not containerized.
Please go to the hero-aem.css file, take the 'we-container' class and put it into your css file. That is the container class for aem.

2024-05-30 13:00 UTC, Matei-Iordache approved these changes

2024-05-30 13:01 UTC, merged