Dex 20729
bitdefender/www-websites pull request #335
Opened 2024-10-28 11:14 UTC by Matei-Iordache

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--www-websites--bitdefender.hlx.page/drafts/matei-test
- After: https://dex-20729--www-websites--bitdefender.hlx.page/drafts/matei-test

2024-10-28 11:15 UTC, enake approved these changes

2024-10-28 11:16 UTC, vradulescu-bd requested changes

2024-10-28 11:16 UTC, vradulescu-bd commented on _src/blocks/hero/hero.css
> +/* block specific CSS goes here */
codefreeze for a bit

2024-10-28 11:18 UTC, vradulescu-bd requested changes

2024-10-28 11:18 UTC, vradulescu-bd commented on _src/styles/styles.css
> +.dex-20729 {
please use Template in the content page

2024-10-28 15:23 UTC, Matei-Iordache commented on _src/styles/styles.css
> +.dex-20729 {
added the template-factory

2024-10-29 10:17 UTC, vradulescu-bd approved these changes

2024-10-29 10:17 UTC, merged