Dex 19682 stage
bitdefender/www-websites pull request #464
Opened 2024-12-18 13:46 UTC by Matei-Iordache

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--www-websites--bitdefender.hlx.page/zh-hk/
- After: https://<branch>--www-websites--bitdefender.hlx.page/zh-hk/

2024-12-18 14:36 UTC, iconstantin-bd requested changes

2024-12-18 14:36 UTC, iconstantin-bd commented on _src/scripts/libs/store/store.js
> +	static $getGeoIpFlag = async () => {
de ce ai folosit $ aici? Voiai sa faci functia privata? @Matei-Iordache

2024-12-18 14:36 UTC, iconstantin-bd commented on _src/scripts/libs/store/store.js
> +		let productPath = campaign !== Constants.NO_PROMOTION ? this.promotionPath : this.defaultPromotionPath;
Te rog adauga si verificarea de this.#isSohoCornerCase(productId) aici!

2024-12-19 12:45 UTC, iconstantin-bd approved these changes

2024-12-20 11:22 UTC, enake approved these changes

2024-12-20 11:25 UTC, merged